### ISSUE TITLE
FetchXml error since October 3, 2021

### ISSUE THREAD

**Issue by syedtabishrizvi** [akaskela/WorkflowElements#10]
![119E8F88-6F6A-43A0-9656-0AAF8D0F9807](https://user-images.githubusercontent.com/22731387/136083182-9912f211-4d6c-4cec-ab57-265e6b1ee8a4.jpeg)

**Comment by syedtabishrizvi** [comment]
@akaskela

**Comment by akaskela** [comment]
@syedtabishrizvi - Is this all queries or just some? Can you share the offending query?

**Comment by akaskela** [comment]
@syedtabishrizvi - are you passing in the query as a user view, system view, or standard Fetch?

**Comment by syedtabishrizvi** [comment]
Standard Fetch



Sent from Yahoo Mail for iPhone


On Wednesday, October 6, 2021, 6:50 am, Aiden Kaskela ***@***.***> wrote:




@syedtabishrizvi - are you passing in the query as a user view, system view, or standard Fetch?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by syedtabishrizvi** [comment]
@akaskela 
Tried to test it with a very simple  WF, getting the same error, pls see the trace. it was working fine in the past.

<fetch distinct="true" useraworderby="false" no-lock="false" mapping="logical">  <entity name="contact">    <attribute name="contactid" />    <attribute name="fullname" />    <attribute name="emailaddress1" />    <attribute name="parentcustomerid" />    <attribute name="telephone1" />    <filter type="and">      <condition attribute="contactid" operator="eq" value="{D4539884-A3DB-EA11-81E2-000D3AD285B1}" />    </filter>  </entity> </fetch>






![image](https://user-images.githubusercontent.com/22731387/136095656-ded51961-65a5-4537-90de-38997c2a262d.png)


Plugin Trace:

[Kaskela.WorkflowElements.Plugins: Kaskela.WorkflowElements.Plugins.Activities.RunWorkflowOnQueriedRecords]
[Kaskela's Workflow Elements: Workflow - Run on Query Results]



Error Message:

Exception type: Microsoft.Crm.CrmException
Message: There was an error executing the FetchXML. Message: ExecuteFetch#api/data
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.<>c__DisplayClass3_0.<Intercept>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.Intercept(IInvocation invocation, IExecutionContext context, SandboxFabricCallTracker sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricCodeUnitExecuteBaseInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.ISandboxFabricCodeUnitProxy.Execute(ILifetimeScope scope, IExecutionContext context, SandboxFabricCallTracker& sandboxFabricCallTracker)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.<>c__DisplayClass5_1.<Execute>b__3()
   at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
   at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
   at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy.Execute[TResult](Func`1 action)
   at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.<>c__DisplayClass13_1.<Execute>b__0()
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
   at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.RemotePluginExecute(IServiceProvider serviceProvider, ILifetimeScope lifetimeScope, IExecutionContext executionContext, ILogger logger)
   at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
   at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
-- End stack trace --

**Comment by akaskela** [comment]
@syedtabishrizvi can you send me the details from [settings gear] -> About? I'm looking for the wave in the header, and the version number halfway down. Also, what's the "usera" property that's cut off in the screenshot?

**Comment by detritus101** [comment]
@akaskela 

Hi, I can report that I am getting the error when using the Rename Document process as well. The plug in had been working perfectly until October 3rd.

The full error details I get from the failed process session is:

> Plugin Trace:
> 
> [Kaskela.WorkflowElements.Plugins: Kaskela.WorkflowElements.Plugins.Activities.DocumentRenameFile]
> [Kaskela's Workflow Elements: Document - Rename Document]
> 
> 
> 
> Error Message:
> 
> Exception type: Microsoft.Crm.CrmException
> Message: There was an error executing the FetchXML. Message: ExecuteFetch#api/data
>    at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.<>c__DisplayClass3_0.<Intercept>b__0()
>    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
>    at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
>    at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricClientTelemetryInterceptor.Intercept(IInvocation invocation, IExecutionContext context, SandboxFabricCallTracker sandboxFabricCallTracker)
>    at Microsoft.Xrm.RemotePlugin.Client.Interceptors.SandboxFabricCodeUnitExecuteBaseInterceptor.Intercept(IInvocation invocation)
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Castle.Proxies.ISandboxFabricCodeUnitProxy.Execute(ILifetimeScope scope, IExecutionContext context, SandboxFabricCallTracker& sandboxFabricCallTracker)
>    at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.<>c__DisplayClass5_1.<Execute>b__3()
>    at Polly.Policy.<>c__DisplayClass150_0`1.<Execute>b__0(Context ctx, CancellationToken ct)
>    at Polly.Policy.<>c__DisplayClass143_0`1.<ExecuteInternal>b__0(Context ctx, CancellationToken ct)
>    at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
>    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
>    at Polly.RetrySyntax.<>c__DisplayClass12_0.<WaitAndRetry>b__0(Action`2 action, Context context, CancellationToken cancellationToken)
>    at Polly.Policy.ExecuteInternal[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
>    at Polly.Policy.Execute[TResult](Func`3 action, Context context, CancellationToken cancellationToken)
>    at Polly.Policy.Execute[TResult](Func`1 action)
>    at Microsoft.Xrm.RemotePlugin.Client.SandboxFabricPlugin.Execute(IServiceProvider serviceProvider)
>    at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.<>c__DisplayClass13_1.<Execute>b__0()
>    at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute(ILogger logger, EventId eventId, ActivityType activityType, Action action, IEnumerable`1 additionalCustomProperties)
>    at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute(ILogger logger, XrmTelemetryActivityType activityType, Action action)
>    at Microsoft.Xrm.RemotePlugin.Client.ResilientSandboxPlugin.Execute(IServiceProvider serviceProvider)
>    at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.RemotePluginExecute(IServiceProvider serviceProvider, ILifetimeScope lifetimeScope, IExecutionContext executionContext, ILogger logger)
>    at Microsoft.Xrm.RemotePlugin.CrmProvider.RemotePlugin.Execute(IServiceProvider serviceProvider)
>    at Microsoft.Crm.Workflow.Services.ProxyCustomActivity.Execute(CodeActivityContext executionContext)
> -- End stack trace --
> 
>

**Comment by wcoomber** [comment]
![9762DC49](https://user-images.githubusercontent.com/5824571/136206937-869c5936-34e8-410b-b160-8c8ce9a12a90.PNG)

**Comment by akaskela** [comment]
My environment is running Server version 9.2.21085.00138 so I haven't gotten the latest update (fetch XML queries and attaching documents are still working fine). I'm going to keep checking on it, hopefully I get the update soon.

**Comment by akaskela** [comment]
@detritus101 and @syedtabishrizvi I got the latest environment but I'm able to do fetch queries, attach docs, and rename docs without issue. Can you email me to dig in a little more? aiden.kaskela [at] exalents.com

**Comment by akaskela** [comment]
Closed - apparently resolved with subsequent Microsoft update.
